# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 565)
        Form.setStatusTip("")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 30, 550, 500))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label.setStyleSheet("border-image: url(:/images/height692_agu33-6457b-medium-.jpg);\n"
"background-color: rgba(0,0,0,200);\n"
"border-top-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 240, 430))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius: 50px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.usernameText = QtWidgets.QLineEdit(self.widget)
        self.usernameText.setGeometry(QtCore.QRect(290, 150, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameText.setFont(font)
        self.usernameText.setStyleSheet("background-color: rgb(0, 0, 0,0);\n"
"border-bottom:2px sold rgba(45,82,101,200);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.usernameText.setObjectName("usernameText")
        self.passwordText = QtWidgets.QLineEdit(self.widget)
        self.passwordText.setGeometry(QtCore.QRect(290, 200, 190, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.passwordText.setFont(font)
        self.passwordText.setStyleSheet("background-color: rgb(0, 0, 0,0);\n"
"border-bottom:2px sold rgba(45,82,101,200);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.passwordText.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordText.setObjectName("passwordText")
        self.loginButton = QtWidgets.QPushButton(self.widget)
        self.loginButton.setGeometry(QtCore.QRect(290, 250, 190, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: rgb(207, 33, 39);\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0  rgba(166, 26, 33), stop:1 rgba(166, 26, 33));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgb(207, 33, 39);\n"
"    \n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.abdullahGulIcon = QtWidgets.QLabel(self.widget)
        self.abdullahGulIcon.setGeometry(QtCore.QRect(290, 60, 190, 60))
        self.abdullahGulIcon.setStyleSheet("image: url(:/images/abdullah_gul-universitesi-logo.png);\n"
"")
        self.abdullahGulIcon.setText("")
        self.abdullahGulIcon.setObjectName("abdullahGulIcon")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(290, 300, 210, 30))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,210);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.usernameText.setPlaceholderText(_translate("Form", " Username"))
        self.passwordText.setPlaceholderText(_translate("Form", " Password"))
        self.loginButton.setText(_translate("Form", "Log in"))
        self.label_3.setText(_translate("Form", "Forget your User Name or password?"))
import res_rc
